/**
 * A hospital already running as a graph, not a waiting-room snapshot.
 *
 * Each person here is a situation the old operating model mishandles:
 * a visit gated by a clock, a discharge that should have started at arrival,
 * an interpreter requested late, work that needs the patient fused with work
 * that does not. The seed writes patients, blockers, evidence, and intents
 * so every surface — plan, inbox, handoffs, companion, command map — has
 * something true to show.
 *
 * `room` is a cubicle label on that floor (208, US-2, 501). The map uses it
 * to place the visit. It is not a second clinical record.
 *
 * Wait clocks freeze at seed so a 31-minute bay stays 31 minutes. Re-seed
 * to pick a new "now."
 */
import { v4 as uuid } from "uuid";
import { writeFileSync, mkdirSync } from "node:fs";
import { db, migrate, addEvent, createBlocker, insertClaim, setMeta } from "./db.js";
import { BLOCKER_TYPES, inferBlockersFromSituation, STATUS_TO_STAGE } from "./src/lib/journey.js";
import { visitKind } from "./src/lib/plan/compile.js";
import { agoSql, freezeAt, toSqlTime } from "./src/lib/clock.js";

migrate();

const origin = Date.now();
freezeAt(origin);
setMeta("frozen_now", new Date(origin).toISOString());

db.prepare(`DELETE FROM audit`).run();
db.prepare(`DELETE FROM claims`).run();
db.prepare(`DELETE FROM escalations`).run();
db.prepare(`DELETE FROM events`).run();
db.prepare(`DELETE FROM blockers`).run();
db.prepare(`DELETE FROM vitals_latest`).run();
db.prepare(`DELETE FROM patients`).run();

function slug(name) {
  return `p-${String(name).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`;
}

const people = [
  // --- Floor 1 · Adult ED bays (double rooms; visits + kit pulls) ---
  {
    name: "Hannah Brooks",
    situation: "Chest pain that started after dinner, I'm 58, I have stents",
    summary: "Second patient in an ED double room. Troponin pending.",
    department: "emergency",
    room: "208",
    floor: "1",
    urgency: "high",
    reason: "Chest pain with prior stents",
    language: "en",
    sentiment: "scared",
    sentimentNote: "Husband in the visitor chair",
    status: "in_progress",
    minutesAgo: 22,
    assigned_to: "Dr. Patel",
    visit_kind: "emergency",
    extraBlockers: [{ type: "lab", title: "Troponin", detail: "Drawn.", offset: 18 }],
    evidence: [
      { kind: "observation", display: "SpO2 94%", proposition: { measure: "spo2", value: 94, display: "94%" }, quote: "Monitor frame: SpO2 94%", source: "monitor" },
    ],
  },
  {
    name: "Robert Chen",
    situation: "Shortness of breath and a racing heart since this morning",
    summary: "In an ED double bay. Sharing the room. Waiting on a repeat ECG.",
    department: "emergency",
    room: "208",
    floor: "1",
    urgency: "high",
    reason: "Dyspnea and palpitations",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Wife is in the chair",
    status: "in_progress",
    minutesAgo: 38,
    assigned_to: "Dr. Patel",
    visit_kind: "emergency",
    extraBlockers: [{ type: "imaging", title: "Repeat ECG", detail: "Machine is on the floor, not in this bay.", offset: 16, can_parallel: 1 }],
  },
  {
    name: "James Carter",
    situation: "Severe chest pain radiating to my left arm, started 20 minutes ago",
    summary: "Chest-pain rule-out. They're on a required 3-hour wait. Freeing a scanner won't shorten it.",
    department: "emergency",
    room: "209",
    floor: "1",
    urgency: "high",
    reason: "Chest pain with arm radiation — possible cardiac emergency",
    language: "en",
    sentiment: "scared",
    sentimentNote: "Came in alone and is visibly frightened",
    status: "in_progress",
    minutesAgo: 31,
    assigned_to: "Dr. Patel",
    visit_kind: "emergency",
    extraBlockers: [
      { type: "lab", title: "Troponin (first)", detail: "Drawn. Analysis running. The second set is gated by a 3-hour interval, not by the lab.", offset: 24 },
      { type: "imaging", title: "ECG", detail: "Tracing done. Cardiology has not been paged.", offset: 26, can_parallel: 1 },
    ],
    evidence: [
      { kind: "observation", display: "SpO2 89%", proposition: { measure: "spo2", value: 89, display: "89%" }, quote: "Monitor frame: SpO2 89%", source: "monitor", consequential: true, confidence: 0.62 },
      { kind: "observation", display: "118/76 mmHg", proposition: { measure: "bp", systolic: 118, diastolic: 76, display: "118/76 mmHg" }, quote: "Blood pressure 118 over 76", source: "spoken" },
      { kind: "intent", display: "Let's get a CT", proposition: { text: "Get a CT" }, quote: "Let's get a CT.", source: "spoken", reversible: true },
    ],
  },
  {
    name: "Diane Shaw",
    situation: "Pressure in my chest when I walk, it stopped in the ambulance but they kept me",
    summary: "Sharing 209. Serial troponin clock is running. The ECG machine is already in the next bay.",
    department: "emergency",
    room: "209",
    floor: "1",
    urgency: "high",
    reason: "Exertional chest pressure",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Daughter on the way",
    status: "in_progress",
    minutesAgo: 44,
    assigned_to: "Dr. Patel",
    visit_kind: "emergency",
    extraBlockers: [{ type: "lab", title: "Troponin (first)", detail: "Drawn. Second set gated by the interval.", offset: 30 }],
  },
  {
    name: "Noah Patel",
    situation: "Fever and a stiff neck since last night, I'm 22",
    summary: "Labs drawn. LP not started. Still occupying an ED bed.",
    department: "emergency",
    room: "210",
    floor: "1",
    urgency: "high",
    reason: "Fever and neck stiffness",
    language: "en",
    sentiment: "scared",
    sentimentNote: "Came with a roommate",
    status: "in_progress",
    minutesAgo: 41,
    visit_kind: "emergency",
    extraBlockers: [
      { type: "lab", title: "Blood culture", detail: "Drawn. Result pending.", offset: 32, can_parallel: 1 },
    ],
    evidence: [
      { kind: "observation", display: "Temp 38.9 °C", proposition: { measure: "temp", value: 38.9, display: "38.9 °C" }, quote: "Temperature 38.9", source: "spoken", consequential: true },
    ],
  },
  {
    name: "Chris Hale",
    situation: "I feel awful, shaking chills, my blood pressure was low in triage",
    summary: "Sepsis work. Cultures drawn. Fluids running. The phlebotomy cart is already in this room.",
    department: "emergency",
    room: "210",
    floor: "1",
    urgency: "high",
    reason: "Suspected sepsis",
    language: "en",
    sentiment: "confused",
    sentimentNote: "Partner at the bedside",
    status: "in_progress",
    minutesAgo: 36,
    visit_kind: "emergency",
    extraBlockers: [
      { type: "lab", title: "Lactate", detail: "Drawn. Result pending.", offset: 20, can_parallel: 1 },
      { type: "pharmacy", title: "Empiric antibiotics", detail: "Order in. Pharmacy has not sent.", offset: 18, can_parallel: 1 },
    ],
  },
  {
    name: "Marcus Johnson",
    situation: "I cut my hand on a table saw, it's still bleeding through the towel",
    summary: "In a double bay with another trauma. Hand surgery consult not started.",
    department: "emergency",
    room: "211",
    floor: "1",
    urgency: "high",
    reason: "Laceration — table saw",
    language: "en",
    sentiment: "in-pain",
    sentimentNote: "Pressure dressing in place",
    status: "in_progress",
    minutesAgo: 27,
    visit_kind: "emergency",
    extraBlockers: [{ type: "consult", title: "Hand surgery consult", detail: "Not assigned.", offset: 20 }],
  },
  {
    name: "Grace Okonkwo",
    situation: "I think I broke my ankle stepping off a curb",
    summary: "X-ray done. Splint not placed. Sharing a bay.",
    department: "emergency",
    room: "211",
    floor: "1",
    urgency: "medium",
    reason: "Ankle injury",
    language: "en",
    sentiment: "in-pain",
    sentimentNote: "Partner is in the visitor chair",
    status: "in_progress",
    minutesAgo: 48,
    visit_kind: "emergency",
    extraBlockers: [{ type: "imaging", title: "Ankle X-ray", detail: "Film taken. Read outstanding.", offset: 22 }],
  },
  {
    name: "Owen Blake",
    situation: "Asthma flare, I already used my inhaler twice, still tight",
    summary: "Nebulizer not in the room. Sharing with a COPD observation.",
    department: "emergency",
    room: "212",
    floor: "1",
    urgency: "medium",
    reason: "Asthma exacerbation",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Sitting forward",
    status: "in_progress",
    minutesAgo: 19,
    visit_kind: "emergency",
    extraBlockers: [{ type: "pharmacy", title: "Nebulized albuterol", detail: "Ordered. Machine not at bedside.", offset: 12, can_parallel: 1 }],
  },
  {
    name: "Tara Nguyen",
    situation: "COPD, I couldn't finish a sentence at home, they started a treatment",
    summary: "Second bed in 212. Needs a nebulizer the same as Owen Blake.",
    department: "emergency",
    room: "212",
    floor: "1",
    urgency: "medium",
    reason: "COPD flare",
    language: "en",
    sentiment: "in-pain",
    sentimentNote: "On home oxygen",
    status: "in_progress",
    minutesAgo: 33,
    visit_kind: "emergency",
  },
  {
    name: "Vic Moretti",
    situation: "I couldn't breathe, they put a tube in in the ambulance",
    summary: "Intubated. Ventilator is what this bay is waiting on. Crash cart already pulled.",
    department: "emergency",
    room: "213",
    floor: "1",
    urgency: "high",
    reason: "Airway — intubated in the field",
    language: "en",
    sentiment: "scared",
    sentimentNote: "Family in the hall",
    status: "in_progress",
    minutesAgo: 14,
    assigned_to: "Dr. Patel",
    visit_kind: "emergency",
    extraBlockers: [
      { type: "consult", title: "ICU bed", detail: "Ventilated. Floor bed not assigned.", offset: 10 },
    ],
    evidence: [
      { kind: "observation", display: "SpO2 91%", proposition: { measure: "spo2", value: 91, display: "91%" }, quote: "Monitor frame: SpO2 91%", source: "monitor", consequential: true },
    ],
  },
  {
    name: "Samir Qureshi",
    situation: "Left side weak since this afternoon, I couldn't talk right",
    summary: "Stroke alert in the second bed. CT already done. Neurology not at the bedside.",
    department: "emergency",
    room: "213",
    floor: "1",
    urgency: "high",
    reason: "Stroke alert",
    language: "en",
    sentiment: "confused",
    sentimentNote: "Wife translating fragments",
    status: "in_progress",
    minutesAgo: 29,
    visit_kind: "emergency",
    extraBlockers: [{ type: "consult", title: "Neurology consult", detail: "Paged. Not arrived.", offset: 18 }],
  },

  // --- Floor 1 · ED waiting / discharge / triage ---
  {
    name: "Sofia Alvarez",
    situation: "Dolor en el pecho desde anoche, no es muy fuerte pero no se quita",
    summary: "ED waiting. Spanish-speaking. Needs an interpreter before the history is useful.",
    department: "emergency",
    room: "South Pavilion",
    floor: "1",
    urgency: "medium",
    reason: "Chest discomfort overnight",
    language: "es",
    sentiment: "anxious",
    sentimentNote: "Daughter translating on the phone",
    status: "waiting",
    minutesAgo: 31,
    visit_kind: "emergency",
    extraBlockers: [{ type: "interpreter", title: "Spanish interpreter", detail: "Queue is backed up.", offset: 24 }],
  },
  {
    name: "Elena Rossi",
    situation: "Migraine for three days, lights make me sick, I vomited in the waiting room",
    summary: "Waiting. Could be in a dark bay. Still in a chair under fluorescents.",
    department: "emergency",
    room: "South Pavilion",
    floor: "1",
    urgency: "medium",
    reason: "Prolonged migraine with vomiting",
    language: "en",
    sentiment: "in-pain",
    sentimentNote: "Sunglasses on indoors",
    status: "waiting",
    minutesAgo: 52,
    visit_kind: "emergency",
  },
  {
    name: "Ben Walsh",
    situation: "Kidney stone, I've had these before, the pain is 9 out of 10",
    summary: "Waiting. Analgesia ordered, not given. Could have been in a chair with a protocol.",
    department: "emergency",
    room: "South Pavilion",
    floor: "1",
    urgency: "high",
    reason: "Recurrent renal colic",
    language: "en",
    sentiment: "in-pain",
    sentimentNote: "Pacing the waiting room",
    status: "waiting",
    minutesAgo: 17,
    visit_kind: "emergency",
  },
  {
    name: "Luis Ortega",
    situation: "Me caí de la bicicleta, me duele el hombro y no lo puedo mover",
    summary: "Waiting. Spanish. Shoulder films not ordered because the history is still untranslated.",
    department: "emergency",
    room: "South Pavilion",
    floor: "1",
    urgency: "medium",
    reason: "Shoulder injury after a fall",
    language: "es",
    sentiment: "in-pain",
    sentimentNote: "Holding the arm",
    status: "waiting",
    minutesAgo: 26,
    visit_kind: "emergency",
    extraBlockers: [{ type: "interpreter", title: "Spanish interpreter", detail: "Same queue as Sofia Alvarez.", offset: 20, can_parallel: 1 }],
  },
  {
    name: "Patricia Cole",
    situation: "Worst headache of my life, it came on all at once",
    summary: "Waiting. High. Could have been in a bay twenty minutes ago.",
    department: "emergency",
    room: "South Pavilion",
    floor: "1",
    urgency: "high",
    reason: "Thunderclap headache",
    language: "en",
    sentiment: "scared",
    sentimentNote: "Husband in the next chair",
    status: "waiting",
    minutesAgo: 21,
    visit_kind: "emergency",
  },
  {
    name: "Dmitri Volkov",
    situation: "У меня сильная боль в животе, меня рвёт с утра",
    summary: "Waiting. Russian. Nobody requested an interpreter at check-in.",
    department: "emergency",
    room: "South Pavilion",
    floor: "1",
    urgency: "medium",
    reason: "Abdominal pain and vomiting",
    language: "ru",
    sentiment: "in-pain",
    sentimentNote: "Came alone",
    status: "waiting",
    minutesAgo: 39,
    visit_kind: "emergency",
    extraBlockers: [{ type: "interpreter", title: "Russian interpreter", detail: "Not requested until the nurse tried English.", offset: 12 }],
  },
  {
    name: "Priya Nair",
    situation: "I think I'm ready to go home but nobody has brought the paperwork",
    summary: "Ready clinically. Discharge paperwork started late. Ride and pharmacy still haven't been started.",
    department: "emergency",
    room: "South Pavilion",
    floor: "1",
    urgency: "low",
    reason: "Disposition ready — discharge stalled on paperwork",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Child at home. Sitting in a wheelchair by the door.",
    status: "pending_signature",
    minutesAgo: 102,
    visit_kind: "emergency",
    extraBlockers: [
      { type: "signature", title: "Attending discharge sign-off", detail: "Note is written. Signature pending 28 min.", offset: 28 },
      { type: "pharmacy", title: "Prescriptions to-go", detail: "Can fill while the signature waits.", offset: 22, can_parallel: 1 },
    ],
    evidence: [
      { kind: "intent", display: "Discharge after the labs", proposition: { text: "Discharge after labs" }, quote: "We can probably discharge after the labs.", source: "spoken", reversible: true },
    ],
  },
  {
    name: "Jordan Lee",
    situation: "They said I can go as soon as the papers are signed, I've been dressed for an hour",
    summary: "Discharge lounge. Ride is in the garage. Signature is not.",
    department: "emergency",
    room: "South Pavilion",
    floor: "1",
    urgency: "low",
    reason: "Ready for discharge",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "In a wheelchair",
    status: "pending_signature",
    minutesAgo: 88,
    visit_kind: "emergency",
    extraBlockers: [{ type: "signature", title: "Discharge sign-off", detail: "Note complete. Attending in a procedure.", offset: 24 }],
  },
  {
    name: "Ibrahim Hassan",
    situation: "I need to get my pre-admission testing done before my surgery next week",
    summary: "Pre-op. Labs can be drawn while registration finishes. Right now they're waiting in a line instead.",
    department: "triage",
    room: "East Pavilion",
    floor: "1",
    urgency: "low",
    reason: "Pre-admission testing for scheduled surgery",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Has paperwork. Surgery is in six days.",
    status: "waiting",
    minutesAgo: 29,
    visit_kind: "preop",
    extraBlockers: [
      { type: "documentation", title: "Pre-operative paperwork", detail: "Consent packet incomplete.", offset: 26, can_parallel: 1 },
      { type: "lab", title: "Pre-op labs", detail: "Can be drawn while registration finishes. Has not been.", offset: 18, can_parallel: 1 },
    ],
  },
  {
    name: "Rachel Cho",
    situation: "Hip replacement on Thursday, they told me to come in for the pre-op physical",
    summary: "Second scheduled surgery in triage. ECG and labs can run in parallel. They are not.",
    department: "triage",
    room: "East Pavilion",
    floor: "1",
    urgency: "low",
    reason: "Pre-op for scheduled hip replacement",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Daughter drove",
    status: "waiting",
    minutesAgo: 41,
    visit_kind: "preop",
    extraBlockers: [{ type: "lab", title: "Type and screen", detail: "Draw station is free.", offset: 20, can_parallel: 1 }],
  },
  {
    name: "Martin Adeyemi",
    situation: "Chest tightness on the bus, they sent me to triage first",
    summary: "Just arrived. High. Still in a triage chair instead of a monitored bay.",
    department: "triage",
    room: "East Pavilion",
    floor: "1",
    urgency: "high",
    reason: "Chest tightness — triage",
    language: "en",
    sentiment: "scared",
    sentimentNote: "Came from work",
    status: "waiting",
    minutesAgo: 8,
    visit_kind: "emergency",
  },
  {
    name: "Ava Brooks",
    situation: "They said a room is coming, I've been in the hall by the desk",
    summary: "Pending a bed. Holding at the nurse station. The bay is clean.",
    department: "emergency",
    room: "South Pavilion",
    floor: "1",
    urgency: "medium",
    reason: "Waiting for a monitored bay",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "On a stretcher in the station",
    status: "pending_bed",
    minutesAgo: 24,
    visit_kind: "emergency",
    extraBlockers: [{ type: "bed", title: "Monitored ED bed", detail: "Turnover is done. Assignment is not.", offset: 16 }],
  },

  // --- Floor 1 · Diagnostics ---
  {
    name: "David Kim",
    situation: "I was in a car accident, my head hurts and I'm dizzy",
    summary: "Head CT is what's holding things up. Transport's done. The read, not the scan, is what delays going home.",
    department: "emergency",
    room: "CT-1",
    floor: "1",
    urgency: "high",
    reason: "Head trauma from car accident — concussion evaluation",
    language: "en",
    sentiment: "confused",
    sentimentNote: "Appears disoriented; may have concussion",
    status: "pending_test",
    minutesAgo: 46,
    visit_kind: "emergency",
    extraBlockers: [
      { type: "imaging", title: "Head CT", detail: "On the table. Radiology has not started the read.", offset: 14 },
    ],
    evidence: [
      { kind: "observation", display: "Pulse 96 bpm", proposition: { measure: "pulse", value: 96, display: "96 bpm" }, quote: "Pulse 96", source: "spoken" },
    ],
  },
  {
    name: "Thomas Greene",
    situation: "I fell off a ladder and my wrist is swollen and painful, can't move it. I use a walker at home.",
    summary: "Likely fracture. X-ray in progress. PT is what's going to delay going home — it takes about three hours and usually gets requested at the end.",
    department: "ypb",
    room: "US-1",
    floor: "1",
    urgency: "medium",
    reason: "Wrist injury from fall — possible fracture",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Family present. Uses a walker at home.",
    status: "pending_test",
    minutesAgo: 28,
    visit_kind: "emergency",
    extraBlockers: [
      { type: "imaging", title: "Wrist X-ray", detail: "Film taken. Ortho follow-up not booked.", offset: 12 },
    ],
  },
  {
    name: "Amara Okafor",
    situation: "I have been having severe abdominal pain for two days, no appetite",
    summary: "CT abdomen is still being read. Surgery is only needed about a third of the time. Next step waits on the read, not the consult.",
    department: "dana",
    room: "US-2",
    floor: "1",
    urgency: "medium",
    reason: "Severe abdominal pain for 2 days",
    language: "en",
    sentiment: "in-pain",
    sentimentNote: "Holding stomach",
    status: "pending_test",
    minutesAgo: 58,
    visit_kind: "emergency",
    extraBlockers: [
      { type: "imaging", title: "CT abdomen", detail: "Acquisition done. Read outstanding.", offset: 16 },
      { type: "lab", title: "Blood panel", detail: "Drawn. Analysis running in parallel with the read.", offset: 42, can_parallel: 1 },
    ],
    evidence: [
      { kind: "intent", display: "I'll call surgery", proposition: { text: "Call surgery" }, quote: "I'll call surgery if the CT looks surgical.", source: "spoken", reversible: true },
    ],
  },
  {
    name: "Nina Park",
    situation: "They want an ultrasound of my belly before surgery decides",
    summary: "FAST / RUQ ultrasound. The cart is not in this cubicle.",
    department: "emergency",
    room: "South Pavilion",
    floor: "1",
    urgency: "medium",
    reason: "Abdominal ultrasound",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "NPO since midnight",
    status: "pending_test",
    minutesAgo: 23,
    visit_kind: "emergency",
    extraBlockers: [{ type: "imaging", title: "Abdominal ultrasound", detail: "Tech assigned. Probe not in the room.", offset: 11 }],
  },
  {
    name: "Wei Zhang",
    situation: "我需要做MRI检查，医生已经开了单子",
    summary: "MRI referral. Calm. Speaks Mandarin. Nobody requested an interpreter because nobody looked at the language field.",
    department: "clinicbldg",
    room: "Clinic Building",
    floor: "1",
    urgency: "low",
    reason: "MRI referral from primary care",
    language: "zh",
    sentiment: "calm",
    sentimentNote: "Paperwork ready",
    status: "waiting",
    minutesAgo: 11,
    visit_kind: "imaging",
    extraBlockers: [{ type: "interpreter", title: "Mandarin interpreter", detail: "Front desk did not request one.", offset: 9, can_parallel: 1 }],
  },

  // --- Floor 1 · Pediatrics / OB overflow ---
  {
    name: "Aisha Rahman",
    situation: "My son has croup, he sounds like a seal when he coughs",
    summary: "In a peds double room. Racemic epinephrine given. Observation continues.",
    department: "pediatric",
    room: "220",
    floor: "1",
    urgency: "medium",
    reason: "Croup",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Father at bedside",
    status: "in_progress",
    minutesAgo: 34,
    visit_kind: "emergency",
  },
  {
    name: "Maya Singh",
    situation: "My toddler has been wheezing since midnight, she won't drink",
    summary: "Sharing a peds double room. Albuterol given. Observation continues.",
    department: "pediatric",
    room: "220",
    floor: "1",
    urgency: "medium",
    reason: "Wheeze — pediatric observation",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Mother at the second bedside",
    status: "in_progress",
    minutesAgo: 27,
    visit_kind: "emergency",
  },
  {
    name: "Fatima Al-Hassan",
    situation: "أنا حامل في الشهر الثامن وأشعر بآلام في البطن",
    summary: "Third-trimester pain. The hold-up is a bed, not the exam. Arabic-speaking, traveling without a partner.",
    department: "pediatric",
    room: "221",
    floor: "1",
    urgency: "medium",
    reason: "Third-trimester abdominal pain",
    language: "ar",
    sentiment: "scared",
    sentimentNote: "Traveling without partner",
    status: "in_progress",
    minutesAgo: 19,
    visit_kind: "obstetric",
    extraBlockers: [
      { type: "bed", title: "Labor & delivery bed", detail: "Evaluation can continue in a monitored obstetric bed, which is not assigned.", offset: 16 },
      { type: "interpreter", title: "Arabic interpreter", detail: "ClearPath can show updates in Arabic. Clinical conversation still needs a person.", offset: 18, can_parallel: 1 },
    ],
  },
  {
    name: "Lila Bennett",
    situation: "My baby has a fever and is pulling at her ear",
    summary: "Sharing 221 with an obstetric overflow. Ear exam can start.",
    department: "pediatric",
    room: "221",
    floor: "1",
    urgency: "medium",
    reason: "Infant fever",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Father holding the child",
    status: "in_progress",
    minutesAgo: 16,
    visit_kind: "emergency",
  },
  {
    name: "Rosa Delgado",
    situation: "Mi hija tiene fiebre muy alta y convulsiones",
    summary: "Child with fever and seizures. Interpreter was requested at the door and still isn't here. We knew the language at check-in.",
    department: "pediatric",
    room: "Children's Hospital",
    floor: "1",
    urgency: "high",
    reason: "Child with high fever and seizures",
    language: "es",
    sentiment: "distressed",
    sentimentNote: "Mother is speaking only Spanish",
    status: "waiting",
    minutesAgo: 18,
    visit_kind: "emergency",
    extraBlockers: [
      { type: "interpreter", title: "Spanish interpreter", detail: "Requested at arrival. Still not at bedside.", offset: 16 },
    ],
    evidence: [
      { kind: "observation", display: "Temp 39.4 °C", proposition: { measure: "temp", value: 39.4, display: "39.4 °C" }, quote: "Temperature 39.4", source: "spoken", consequential: true },
    ],
  },
  {
    name: "Leo Nakamura",
    situation: "My daughter fell off the playground and her arm looks wrong",
    summary: "Peds waiting. X-ray not ordered yet.",
    department: "pediatric",
    room: "Children's Hospital",
    floor: "1",
    urgency: "medium",
    reason: "Forearm injury after a fall",
    language: "en",
    sentiment: "distressed",
    sentimentNote: "Child is crying; mother is calm",
    status: "waiting",
    minutesAgo: 14,
    visit_kind: "emergency",
  },
  {
    name: "Noelle Baptiste",
    situation: "Pitit mwen an ap respire mal, li gen lafèv",
    summary: "Peds waiting. Haitian Creole. Respiratory distress. Interpreter not requested.",
    department: "pediatric",
    room: "Children's Hospital",
    floor: "1",
    urgency: "high",
    reason: "Pediatric respiratory distress",
    language: "ht",
    sentiment: "distressed",
    sentimentNote: "Mother holding the child upright",
    status: "waiting",
    minutesAgo: 12,
    visit_kind: "emergency",
    extraBlockers: [{ type: "interpreter", title: "Haitian Creole interpreter", detail: "Not requested at the door.", offset: 10 }],
  },
  {
    name: "Harper Diaz",
    situation: "Allergic reaction, face is swelling, they gave epinephrine at the door",
    summary: "In a peds bay. Airway cart should already be here.",
    department: "pediatric",
    room: "222",
    floor: "1",
    urgency: "high",
    reason: "Anaphylaxis",
    language: "en",
    sentiment: "scared",
    sentimentNote: "Epi given; observation continues",
    status: "in_progress",
    minutesAgo: 11,
    visit_kind: "emergency",
    extraBlockers: [{ type: "pharmacy", title: "Second epinephrine", detail: "Can draw now. Has not been.", offset: 8, can_parallel: 1 }],
  },
  {
    name: "Theo Klein",
    situation: "Swallowed a coin, he is drooling, x-ray is done",
    summary: "Sharing 222. Film taken. ENT not called.",
    department: "pediatric",
    room: "222",
    floor: "1",
    urgency: "medium",
    reason: "Foreign body — coin",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Father filming the monitor",
    status: "in_progress",
    minutesAgo: 37,
    visit_kind: "emergency",
    extraBlockers: [{ type: "imaging", title: "Neck X-ray", detail: "Film taken. ENT consult not placed.", offset: 15 }],
  },
  {
    name: "Imani Cole",
    situation: "Sickle cell pain crisis, we've been here before",
    summary: "Peds bay. Fluids running. Next dose of analgesia is late.",
    department: "pediatric",
    room: "223",
    floor: "1",
    urgency: "high",
    reason: "Sickle cell pain crisis",
    language: "en",
    sentiment: "in-pain",
    sentimentNote: "Mother knows the protocol",
    status: "in_progress",
    minutesAgo: 63,
    visit_kind: "emergency",
    extraBlockers: [{ type: "pharmacy", title: "IV analgesia", detail: "Due. Not given.", offset: 25 }],
  },
  {
    name: "Mateo Ruiz",
    situation: "Gastro, he hasn't kept anything down since last night",
    summary: "Second bed in 223. Ondansetron given. Observation continues.",
    department: "pediatric",
    room: "223",
    floor: "1",
    urgency: "medium",
    reason: "Pediatric gastroenteritis",
    language: "es",
    sentiment: "anxious",
    sentimentNote: "Father at bedside; English is enough for this visit",
    status: "in_progress",
    minutesAgo: 45,
    visit_kind: "emergency",
  },

  // --- Floor 1 · Rabies / North / Dana / YPB / Winchester ---
  {
    name: "Maria Santos",
    situation: "Dog bite on my hand, the dog was a stray and I don't know if it was vaccinated",
    summary: "Rabies shots. Pharmacy is mixing a weight-based dose we could have called in from triage.",
    department: "rabies",
    room: "A3",
    floor: "1",
    urgency: "medium",
    reason: "Stray dog bite — rabies vaccine assessment",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Worried about rabies",
    status: "in_progress",
    minutesAgo: 21,
    visit_kind: "emergency",
    extraBlockers: [
      { type: "pharmacy", title: "Rabies immunoglobulin", detail: "Weight-based dose. Pharmacy started late because nobody pre-alerted them.", offset: 12 },
    ],
  },
  {
    name: "Michael Torres",
    situation: "bat flew into my house last night and scratched my arm while I was trying to get it out",
    summary: "Same clinic, same pharmacy, same kind of dose as Maria Santos. Two visits, one prep if anyone notices.",
    department: "rabies",
    room: "Rabies Vaccine Clinic",
    floor: "1",
    urgency: "medium",
    reason: "Bat scratch — rabies post-exposure evaluation",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Read about rabies online",
    status: "waiting",
    minutesAgo: 9,
    visit_kind: "emergency",
  },
  {
    name: "Samuel Osei",
    situation: "Je dois faire une mammographie de routine",
    summary: "Routine imaging. Waiting on a 15-minute ride between buildings.",
    department: "north",
    room: "North Pavilion",
    floor: "1",
    urgency: "low",
    reason: "Routine mammography screening",
    language: "ht",
    sentiment: "calm",
    sentimentNote: "Language recorded as French; Haitian Creole is the closer supported match.",
    status: "pending_transport",
    minutesAgo: 18,
    visit_kind: "imaging",
    extraBlockers: [
      { type: "transport", title: "Transport to North Pavilion", detail: "Destination is ready. The patient is not moving.", offset: 14 },
    ],
  },
  {
    name: "Helen Cho",
    situation: "Diagnostic mammogram, they found something on screening last week",
    summary: "In North 301. Tech is with another patient.",
    department: "north",
    room: "301",
    floor: "1",
    urgency: "low",
    reason: "Diagnostic mammography",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Brought prior films",
    status: "in_progress",
    minutesAgo: 26,
    visit_kind: "imaging",
  },
  {
    name: "Ruth Adeyemi",
    situation: "Breast ultrasound after the mammogram, I'm already changed",
    summary: "Room 302. Ultrasound is the appointment. The cart is in US-1.",
    department: "north",
    room: "302",
    floor: "1",
    urgency: "low",
    reason: "Breast ultrasound",
    language: "en",
    sentiment: "calm",
    sentimentNote: "On time",
    status: "in_progress",
    minutesAgo: 15,
    visit_kind: "imaging",
    extraBlockers: [{ type: "imaging", title: "Breast ultrasound", detail: "Room is ready. Probe is not.", offset: 8 }],
  },
  {
    name: "Carol Nguyen",
    situation: "Biopsy consult, they put me in a North room",
    summary: "Room 303. Consent is written. Signature is not.",
    department: "north",
    room: "303",
    floor: "1",
    urgency: "low",
    reason: "Biopsy consult",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Sister in the chair",
    status: "in_progress",
    minutesAgo: 33,
    visit_kind: "clinic",
    extraBlockers: [{ type: "signature", title: "Procedure consent", detail: "Form is printed.", offset: 12 }],
  },
  {
    name: "Priya Shah",
    situation: "Dermatology procedure, they numbed the area already",
    summary: "Dana 110. Procedure tray should be in the room.",
    department: "dana",
    room: "110",
    floor: "1",
    urgency: "low",
    reason: "Skin procedure",
    language: "en",
    sentiment: "calm",
    sentimentNote: "On lunch break from work",
    status: "in_progress",
    minutesAgo: 22,
    visit_kind: "clinic",
    extraBlockers: [{ type: "consult", title: "Dermatology procedure", detail: "Attending in the next room.", offset: 10 }],
  },
  {
    name: "Jonah Klein",
    situation: "Infusion, the chair is mine for the next hour",
    summary: "Dana 111. Pump is in the room. Pharmacy has not sent the bag.",
    department: "dana",
    room: "111",
    floor: "1",
    urgency: "low",
    reason: "Outpatient infusion",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Reading",
    status: "in_progress",
    minutesAgo: 48,
    visit_kind: "clinic",
    extraBlockers: [{ type: "pharmacy", title: "Infusion bag", detail: "Mixed. Not delivered.", offset: 20 }],
  },
  {
    name: "Sasha Miller",
    situation: "Ortho follow-up for the wrist, they want another look",
    summary: "YPB 120. Thomas Greene's films are still in diagnostics.",
    department: "ypb",
    room: "120",
    floor: "1",
    urgency: "low",
    reason: "Ortho follow-up",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Cast in place",
    status: "in_progress",
    minutesAgo: 17,
    visit_kind: "clinic",
  },
  {
    name: "Evan Brooks",
    situation: "They need to suture a small laceration from a kitchen knife",
    summary: "YPB 121. Procedure tray is the need. Not a trauma bay.",
    department: "ypb",
    room: "121",
    floor: "1",
    urgency: "medium",
    reason: "Suture — kitchen laceration",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Tetanus is current",
    status: "in_progress",
    minutesAgo: 13,
    visit_kind: "emergency",
    extraBlockers: [{ type: "consult", title: "Wound repair", detail: "Tray not in the room.", offset: 8 }],
  },
  {
    name: "Carlos Mendez",
    situation: "Necesito ver a un psiquiatra, he tenido pensamientos muy difíciles",
    summary: "Psych evaluation. Placement is what's slow, and it hasn't started. Shouldn't wait in a public line.",
    department: "winchester",
    room: "Winchester Building",
    floor: "1",
    urgency: "medium",
    reason: "Psychiatric evaluation — difficult thoughts",
    language: "es",
    sentiment: "anxious",
    sentimentNote: "Withdrawn. Needs a quiet handoff.",
    status: "waiting",
    minutesAgo: 22,
    visit_kind: "behavioral",
    extraBlockers: [
      { type: "consult", title: "Psychiatry evaluation", detail: "Specialist not yet assigned.", offset: 14 },
      { type: "interpreter", title: "Spanish interpreter", detail: "Clinical conversation cannot start without one.", offset: 20, can_parallel: 1 },
    ],
  },
  {
    name: "Anna Kowalski",
    situation: "I have been feeling very sad and isolated for months, my family made me come",
    summary: "In evaluation. Safety plan and placement can start before we decide next steps. They haven't.",
    department: "winchester",
    room: "401",
    floor: "1",
    urgency: "medium",
    reason: "Depression evaluation",
    language: "en",
    sentiment: "distressed",
    sentimentNote: "Family is in the waiting area",
    status: "in_progress",
    minutesAgo: 51,
    visit_kind: "behavioral",
    extraBlockers: [
      { type: "consult", title: "Psychiatry evaluation", detail: "With the psychiatrist now.", offset: 22 },
    ],
  },
  {
    name: "Jonah Reed",
    situation: "Panic attack at work, they sent me here instead of the ED",
    summary: "Sharing 401. Quiet room. Placement not started.",
    department: "winchester",
    room: "401",
    floor: "1",
    urgency: "medium",
    reason: "Panic — behavioral evaluation",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Friend in the chair",
    status: "in_progress",
    minutesAgo: 33,
    visit_kind: "behavioral",
  },
  {
    name: "Leah Ortiz",
    situation: "They want to watch me overnight after the suicidal thoughts",
    summary: "Winchester 402. Safety plan written. Bed on the psych floor is not.",
    department: "winchester",
    room: "402",
    floor: "1",
    urgency: "medium",
    reason: "Safety observation",
    language: "es",
    sentiment: "distressed",
    sentimentNote: "Sister in the second chair",
    status: "in_progress",
    minutesAgo: 67,
    visit_kind: "behavioral",
    extraBlockers: [{ type: "bed", title: "Inpatient psych bed", detail: "Evaluated. Placement not started.", offset: 40 }],
  },
  {
    name: "Noah Green",
    situation: "Substance use, I asked for help, they put me in a quiet room",
    summary: "Second bed in 402. Social work not assigned.",
    department: "winchester",
    room: "402",
    floor: "1",
    urgency: "medium",
    reason: "Substance use evaluation",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Came on his own",
    status: "in_progress",
    minutesAgo: 42,
    visit_kind: "behavioral",
    extraBlockers: [{ type: "consult", title: "Social work", detail: "Not assigned.", offset: 18 }],
  },

  // --- Floor 2 · Observation ---
  {
    name: "Omar Haddad",
    situation: "I was kept overnight for observation after an asthma flare",
    summary: "Observation double room on Fitkin 2. Ready to go. Paperwork isn't.",
    department: "fitkin",
    room: "501",
    floor: "2",
    urgency: "medium",
    reason: "Asthma observation",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Family in the second chair",
    status: "in_progress",
    minutesAgo: 118,
    visit_kind: "emergency",
    extraBlockers: [{ type: "documentation", title: "Discharge paperwork", detail: "Can start now.", offset: 42, can_parallel: 1 }],
  },
  {
    name: "Leela Menon",
    situation: "COPD flare, they kept me on Fitkin overnight for breathing treatments",
    summary: "Observation double room. Ready for discharge teaching. Nobody has started it.",
    department: "fitkin",
    room: "501",
    floor: "2",
    urgency: "medium",
    reason: "COPD observation",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Husband in the chair",
    status: "in_progress",
    minutesAgo: 104,
    visit_kind: "emergency",
    extraBlockers: [{ type: "documentation", title: "Discharge teaching", detail: "Can start now.", offset: 28, can_parallel: 1 }],
  },
  {
    name: "Ruth Klein",
    situation: "I had a syncopal episode in the cafeteria, they put me in observation",
    summary: "Sharing an observation room. Telemetry is quiet. Telemetry read is not.",
    department: "fitkin",
    room: "502",
    floor: "2",
    urgency: "medium",
    reason: "Syncope — observation",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Son is with her",
    status: "in_progress",
    minutesAgo: 76,
    visit_kind: "emergency",
    extraBlockers: [{ type: "consult", title: "Cardiology review of telemetry", detail: "Strip is sitting in a queue.", offset: 38 }],
  },
  {
    name: "Tomas Berg",
    situation: "They want to watch my heart overnight after the palpitations",
    summary: "Sharing observation. Telemetry is quiet. The read is not.",
    department: "fitkin",
    room: "502",
    floor: "2",
    urgency: "medium",
    reason: "Telemetry observation",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Daughter stepped out for coffee",
    status: "in_progress",
    minutesAgo: 91,
    visit_kind: "emergency",
  },
  {
    name: "Nadia Solis",
    situation: "Post-procedure observation after the IR drain, I feel fine",
    summary: "Observation double. Diet is written. Walk order is not.",
    department: "fitkin",
    room: "503",
    floor: "2",
    urgency: "low",
    reason: "Post-procedure observation",
    language: "es",
    sentiment: "calm",
    sentimentNote: "Sister at bedside",
    status: "in_progress",
    minutesAgo: 64,
    visit_kind: "clinic",
  },
  {
    name: "Walter Kim",
    situation: "Cellulitis of the leg, they started IV antibiotics and want another look in the morning",
    summary: "Second bed in an observation room. Pharmacy already sent the next dose.",
    department: "fitkin",
    room: "503",
    floor: "2",
    urgency: "medium",
    reason: "Cellulitis observation",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Watching the TV",
    status: "in_progress",
    minutesAgo: 71,
    visit_kind: "emergency",
  },
  {
    name: "Greta Holm",
    situation: "GI bleed overnight, the second hemoglobin is still pending",
    summary: "Room 504. Serial labs. Phlebotomy can draw now.",
    department: "fitkin",
    room: "504",
    floor: "2",
    urgency: "high",
    reason: "GI bleed observation",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Husband asleep in the chair",
    status: "in_progress",
    minutesAgo: 206,
    visit_kind: "emergency",
    extraBlockers: [{ type: "lab", title: "Repeat hemoglobin", detail: "Due. Not drawn.", offset: 50 }],
    evidence: [
      { kind: "observation", display: "Pulse 108 bpm", proposition: { measure: "pulse", value: 108, display: "108 bpm" }, quote: "Pulse 108", source: "monitor" },
    ],
  },
  {
    name: "Paul Nguyen",
    situation: "They kept me after the transfusion to watch a reaction",
    summary: "Sharing 504. Pump is running. Next set of vitals is on the monitor.",
    department: "fitkin",
    room: "504",
    floor: "2",
    urgency: "medium",
    reason: "Post-transfusion observation",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Reading",
    status: "in_progress",
    minutesAgo: 83,
    visit_kind: "emergency",
  },
  {
    name: "Irene Walsh",
    situation: "CHF, they diuresed me overnight, I can go if the weight is down",
    summary: "Room 505. Discharge teaching not started. Telemetry still on.",
    department: "fitkin",
    room: "505",
    floor: "2",
    urgency: "medium",
    reason: "Heart failure observation",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Wants to go home today",
    status: "in_progress",
    minutesAgo: 312,
    visit_kind: "emergency",
    extraBlockers: [
      { type: "documentation", title: "Discharge teaching", detail: "Weight is down. Teaching not started.", offset: 40, can_parallel: 1 },
      { type: "consult", title: "Cardiology sign-off", detail: "Strip is quiet.", offset: 55 },
    ],
  },
  {
    name: "Harold Peck",
    situation: "Pneumonia, oxygen is 2 liters, they want another chest film in the morning",
    summary: "Sharing 505. Portable x-ray is the morning appointment.",
    department: "fitkin",
    room: "505",
    floor: "2",
    urgency: "medium",
    reason: "Pneumonia observation",
    language: "en",
    sentiment: "calm",
    sentimentNote: "On 2 L nasal cannula",
    status: "in_progress",
    minutesAgo: 268,
    visit_kind: "emergency",
    extraBlockers: [{ type: "imaging", title: "Morning chest x-ray", detail: "Ordered for 06:00. Not taken.", offset: 30 }],
  },
  {
    name: "Yara Haddad",
    situation: "Pyelo, IV antibiotics, I feel better",
    summary: "Room 506. Pharmacy sent the next dose. Culture is pending.",
    department: "fitkin",
    room: "506",
    floor: "2",
    urgency: "medium",
    reason: "Pyelonephritis observation",
    language: "ar",
    sentiment: "calm",
    sentimentNote: "English is enough for this visit",
    status: "in_progress",
    minutesAgo: 97,
    visit_kind: "emergency",
    extraBlockers: [{ type: "lab", title: "Urine culture", detail: "Pending.", offset: 80, can_parallel: 1 }],
  },
  {
    name: "Colin Hart",
    situation: "Alcohol withdrawal protocol, vitals every hour",
    summary: "Sharing 506. CIWA is quiet. The next set is due.",
    department: "fitkin",
    room: "506",
    floor: "2",
    urgency: "medium",
    reason: "Withdrawal observation",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Friend stepped out",
    status: "in_progress",
    minutesAgo: 142,
    visit_kind: "emergency",
  },

  // --- Floor 2 · PFT / MRI / lab / pharmacy / eye / consults ---
  {
    name: "Peter Novak",
    situation: "Pulmonary function test, my pulmonologist booked it weeks ago",
    summary: "On Fitkin 2. In the PFT bay. Tech is with another patient.",
    department: "fitkin",
    room: "PFT-1",
    floor: "2",
    urgency: "low",
    reason: "Scheduled pulmonary function test",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Brought inhalers",
    status: "in_progress",
    minutesAgo: 21,
    visit_kind: "clinic",
  },
  {
    name: "Amara Diallo",
    situation: "I'm here for the ECG and breathing test my pulmonologist booked together",
    summary: "In the PFT suite. Tech is finishing the last patient.",
    department: "fitkin",
    room: "PFT-2",
    floor: "2",
    urgency: "low",
    reason: "ECG and pulmonary function",
    language: "en",
    sentiment: "calm",
    sentimentNote: "On time",
    status: "in_progress",
    minutesAgo: 16,
    visit_kind: "clinic",
  },
  {
    name: "Linda Hoffman",
    situation: "I need a pulmonary function test, my doctor referred me. I get short of breath climbing stairs.",
    summary: "Routine breathing test. Short wait. ECG can be done in the chair if someone sends the machine.",
    department: "fitkin",
    room: "Fitkin Building",
    floor: "2",
    urgency: "low",
    reason: "Routine pulmonary function test",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Relaxed, routine appointment",
    status: "waiting",
    minutesAgo: 12,
    visit_kind: "clinic",
  },
  {
    name: "Yuki Tanaka",
    situation: "I am here for an ECG my cardiologist ordered",
    summary: "Fitkin waiting. Slot is open. Nobody called her.",
    department: "fitkin",
    room: "ECG-1",
    floor: "2",
    urgency: "low",
    reason: "Scheduled ECG",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Reading",
    status: "called",
    minutesAgo: 19,
    visit_kind: "clinic",
  },
  {
    name: "Marcus Ade",
    situation: "Holter hookup, they said it takes ten minutes",
    summary: "ECG-2. Telemetry pack is the appointment.",
    department: "fitkin",
    room: "ECG-2",
    floor: "2",
    urgency: "low",
    reason: "Holter hookup",
    language: "en",
    sentiment: "calm",
    sentimentNote: "On lunch break",
    status: "in_progress",
    minutesAgo: 9,
    visit_kind: "clinic",
    extraBlockers: [{ type: "consult", title: "Cardiology hookup", detail: "Tech is with Yuki Tanaka.", offset: 6 }],
  },
  {
    name: "Claire Dubois",
    situation: "MRI of my lumbar spine, chronic back pain, I already changed",
    summary: "On the MRI table. Tech stepped out. Clock is running.",
    department: "fitkin",
    room: "MRI-1",
    floor: "2",
    urgency: "low",
    reason: "Lumbar MRI",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Claustrophobic but managing",
    status: "pending_test",
    minutesAgo: 34,
    visit_kind: "imaging",
    extraBlockers: [{ type: "imaging", title: "Lumbar MRI", detail: "Acquisition paused.", offset: 11 }],
  },
  {
    name: "Pauline Ortiz",
    situation: "Brain MRI, headaches for a month, I already filled the screening form",
    summary: "US-3 holding for MRI. Contrast not drawn.",
    department: "fitkin",
    room: "US-3",
    floor: "2",
    urgency: "low",
    reason: "Brain MRI",
    language: "es",
    sentiment: "calm",
    sentimentNote: "Changed; waiting on contrast",
    status: "pending_test",
    minutesAgo: 27,
    visit_kind: "imaging",
    extraBlockers: [
      { type: "imaging", title: "Brain MRI", detail: "Table is free after Claire Dubois.", offset: 8 },
      { type: "lab", title: "Creatinine before contrast", detail: "Not drawn.", offset: 20, can_parallel: 1 },
    ],
  },
  {
    name: "Kenji Mori",
    situation: "Just a blood draw, they sent me upstairs to the lab",
    summary: "In a Fitkin lab chair. Tube labels are printed.",
    department: "fitkin",
    room: "Draw-1",
    floor: "2",
    urgency: "low",
    reason: "Lab phlebotomy",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Has a printed order",
    status: "pending_test",
    minutesAgo: 8,
    visit_kind: "preop",
    extraBlockers: [{ type: "lab", title: "Blood draw", detail: "Chair is free.", offset: 6, can_parallel: 1 }],
  },
  {
    name: "Daniel Okeke",
    situation: "Blood draw for my pre-op labs, I already checked in downstairs",
    summary: "Lab on 2. Second chair. Labels printed.",
    department: "fitkin",
    room: "Draw-2",
    floor: "2",
    urgency: "low",
    reason: "Pre-op phlebotomy",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Has a printed order",
    status: "pending_test",
    minutesAgo: 14,
    visit_kind: "preop",
    extraBlockers: [{ type: "lab", title: "Pre-op blood draw", detail: "Draw station is free.", offset: 10, can_parallel: 1 }],
  },
  {
    name: "Jamal Wright",
    situation: "I need my prescription from the Fitkin pharmacy before I can leave",
    summary: "Pharmacy window on 2. Discharge meds not filled.",
    department: "fitkin",
    room: "Fitkin Bldg",
    floor: "2",
    urgency: "low",
    reason: "Discharge medications",
    language: "en",
    sentiment: "anxious",
    sentimentNote: "Ride is downstairs",
    status: "waiting",
    minutesAgo: 27,
    visit_kind: "clinic",
    extraBlockers: [{ type: "pharmacy", title: "To-go medications", detail: "Queue at the window.", offset: 22 }],
  },
  {
    name: "George Ellis",
    situation: "They want another set of films, I have to go back to x-ray",
    summary: "Transport between Fitkin rooms. The destination is ready.",
    department: "fitkin",
    room: "Fitkin Bldg",
    floor: "2",
    urgency: "low",
    reason: "Repeat films",
    language: "en",
    sentiment: "calm",
    sentimentNote: "In a wheelchair",
    status: "pending_transport",
    minutesAgo: 11,
    visit_kind: "imaging",
    extraBlockers: [{ type: "transport", title: "Transport to x-ray", detail: "Requested.", offset: 8 }],
  },
  {
    name: "Helen Park",
    situation: "I've had blurry vision for a week and my optometrist said to come here",
    summary: "Called. Room is ready. Nothing's actually pending except the walk.",
    department: "dana",
    room: "210",
    floor: "2",
    urgency: "low",
    reason: "Vision changes — ophthalmology referral",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Brought a referral letter",
    status: "called",
    minutesAgo: 9,
    visit_kind: "clinic",
  },
  {
    name: "Andre Silva",
    situation: "Drops for the dilated eye exam, I can't see to walk out yet",
    summary: "In an ophthalmology room on 2. Waiting out the dilation.",
    department: "dana",
    room: "211",
    floor: "2",
    urgency: "low",
    reason: "Dilated eye exam",
    language: "pt",
    sentiment: "calm",
    sentimentNote: "Sunglasses in his pocket",
    status: "in_progress",
    minutesAgo: 24,
    visit_kind: "clinic",
  },
  {
    name: "Mei Lin",
    situation: "Follow-up for the blurry vision, they sent me to Dana on 2",
    summary: "Ophthalmology. Helen Park was already called into the same suite.",
    department: "dana",
    room: "212",
    floor: "2",
    urgency: "low",
    reason: "Ophthalmology follow-up",
    language: "zh",
    sentiment: "calm",
    sentimentNote: "Needs an interpreter for the exam",
    status: "in_progress",
    minutesAgo: 20,
    visit_kind: "clinic",
    extraBlockers: [{ type: "interpreter", title: "Mandarin interpreter", detail: "Clinic did not request one.", offset: 16 }],
  },
  {
    name: "Fatima El-Sayed",
    situation: "Follow-up with the specialist, they put me in a consult room",
    summary: "Consult room on 2. Attending is in the other room.",
    department: "ypb",
    room: "220",
    floor: "2",
    urgency: "low",
    reason: "Specialty consult",
    language: "ar",
    sentiment: "calm",
    sentimentNote: "Family in the second chair",
    status: "in_progress",
    minutesAgo: 18,
    visit_kind: "clinic",
  },
  {
    name: "Owen Grant",
    situation: "Pre-op history and physical for the hernia repair on Friday",
    summary: "Consult 221. Scheduled surgery clearance. ECG not in the room.",
    department: "ypb",
    room: "221",
    floor: "2",
    urgency: "low",
    reason: "Pre-op H&P for scheduled hernia repair",
    language: "en",
    sentiment: "calm",
    sentimentNote: "Brought the surgical packet",
    status: "in_progress",
    minutesAgo: 25,
    visit_kind: "preop",
    extraBlockers: [
      { type: "documentation", title: "Surgical clearance", detail: "H&P half written.", offset: 14, can_parallel: 1 },
      { type: "lab", title: "Pre-op labs", detail: "Can draw upstairs. Has not been sent.", offset: 12, can_parallel: 1 },
    ],
  },
];

const insert = db.prepare(`
  INSERT INTO patients (
    id, name, situation, summary, department, room, floor,
    urgency, reason, phone, language, sentiment, sentimentNote,
    queue_position, status, stage, share_token, assigned_to, visit_kind,
    checked_in_at, last_updated_at
  ) VALUES (
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?
  )
`);

const counts = {};
let evidenceCount = 0;
const demo = [];

for (const p of people) {
  const id = p.id || slug(p.name);
  const token = uuid().slice(0, 8);
  const kind = p.visit_kind || visitKind(p);
  counts[p.department] = (counts[p.department] || 0) + 1;
  const checkedIn = agoSql(p.minutesAgo, origin);
  const updated = agoSql(p.updatedAgo ?? p.minutesAgo, origin);
  const stage = STATUS_TO_STAGE[p.status] || "waiting";

  insert.run(
    id, p.name, p.situation, p.summary,
    p.department, p.room, p.floor,
    p.urgency, p.reason,
    "", p.language, p.sentiment, p.sentimentNote,
    counts[p.department], p.status, stage, token, p.assigned_to || null, kind,
    checkedIn, updated
  );

  addEvent(id, "checkin", "Checked in", p.reason);
  if (p.status !== "waiting") addEvent(id, "status", `Now ${p.status.replaceAll("_", " ")}`);

  const specs = p.extraBlockers || inferBlockersFromSituation({ ...p, id });
  for (const spec of specs) {
    const meta = BLOCKER_TYPES[spec.type] || {};
    const blocker = createBlocker(id, {
      type: spec.type,
      title: spec.title,
      detail: spec.detail,
      owner_role: spec.owner_role || meta.owner,
      eta_minutes: spec.eta_minutes || meta.typicalMins,
      can_parallel: spec.can_parallel === 0 ? 0 : 1,
    });
    if (spec.offset) {
      db.prepare(`UPDATE blockers SET created_at=? WHERE id=?`)
        .run(agoSql(spec.offset, origin), blocker.id);
    }
  }

  for (const claim of p.evidence || []) {
    insertClaim({
      patientId: id,
      fingerprint: `${id}:${claim.display}`,
      kind: claim.kind,
      layer: claim.kind === "intent" ? "interpretation" : "observation",
      display: claim.display,
      proposition: claim.proposition,
      evidence: { source: claim.source, quote: claim.quote, speaker: "bedside", room: p.room, synthetic: true },
      confidence: claim.confidence ?? 0.7,
      consequential: Boolean(claim.consequential),
      reversible: Boolean(claim.reversible),
    });
    evidenceCount += 1;
  }

  demo.push({
    name: p.name,
    visitKind: kind,
    status: p.status,
    language: p.language,
    room: p.room,
    floor: p.floor,
    waitMinutes: p.minutesAgo,
    follow: `/follow/${token}`,
    situation: p.situation,
    demonstrates: p.summary,
    capture: (p.evidence || []).map((c) => c.quote).filter(Boolean),
  });
}

const usage = {
  generatedAt: new Date().toISOString(),
  howToLook: {
    staff: "http://localhost:5173/dashboard",
    operate: "Open Operate. The first card is the next reversible move, or an instruction to leave the floor alone.",
    evidence: "Open Evidence. SpO2 89% on James Carter is consequential and unverified. Batch confirm does not include it.",
    companion: "Any follow URL below is a caregiver view of the same plan, without the medical story.",
    map: "Command Map. One overlay per room. Opening a room lists visits, required supplies, and Request equipment.",
  },
  sampleRequests: {
    spokenRound: "Pulse 72. SpO2 98%. Blood pressure 118 over 76. Temperature 36.6. Respiratory rate 16.",
    capture: "POST /api/evidence/capture { patientId, text, speaker: 'nurse' }",
    stageMove: "POST /api/control/stage  — stages the recommended reversible move; refused if it is clinical",
    patientPlan: "GET /api/patients/:id/plan",
    floor: "GET /api/floor",
  },
  patients: demo,
};

mkdirSync("examples", { recursive: true });
writeFileSync("examples/demo.json", JSON.stringify(usage, null, 2));

console.log(`Seeded ${people.length} patients, ${evidenceCount} evidence claims`);
console.log(`Clock frozen at ${toSqlTime(origin)}`);
for (const [dept, n] of Object.entries(counts)) console.log(`  ${dept}: ${n}`);
console.log("Wrote examples/demo.json");
for (const row of demo.slice(0, 8)) {
  console.log(`  ${row.name} [${row.visitKind}] ${row.room} · ${row.waitMinutes}m ${row.follow}`);
}
